/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#be5066",
        "tertiary-fixed-dim": "#e9c349",
        "on-secondary": "#ffffff",
        "surface-dim": "#ebd4e1",
        "secondary": "#7a4c8e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4e3d00",
        "surface-container-highest": "#f4dcea",
        "on-secondary-fixed-variant": "#603475",
        "inverse-primary": "#ffb2bc",
        "on-background": "#251721",
        "on-primary": "#ffffff",
        "surface-variant": "#f4dcea",
        "secondary-container": "#e9b3fe",
        "surface": "#fff7f9",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#fff7f9",
        "on-primary-fixed": "#400013",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#cca72f",
        "inverse-surface": "#3b2c36",
        "primary": "#9e384e",
        "outline": "#897174",
        "secondary-fixed": "#f7d8ff",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#574500",
        "on-error": "#ffffff",
        "on-surface-variant": "#554244",
        "on-surface": "#251721",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#300246",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffe088",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6d4082",
        "outline-variant": "#dcc0c2",
        "on-primary-fixed-variant": "#82223a",
        "surface-container-high": "#fae2f0",
        "tertiary": "#735c00",
        "secondary-fixed-dim": "#e9b3fe",
        "surface-container": "#ffe7f5",
        "primary-fixed": "#ffd9dd",
        "surface-container-low": "#fff0f7",
        "background": "#fff7f9",
        "inverse-on-surface": "#ffecf6",
        "surface-tint": "#a13a51",
        "primary-fixed-dim": "#ffb2bc",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "margin-lg": "3.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-md": "1.5rem",
        "gutter-lg": "2rem",
        margin: "1rem",
        "space-md": "1rem",
        "margin-md": "2rem",
        gutter: "1rem",
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "currency-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Playfair Display"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "headline-md": ["26px", { lineHeight: "32px", fontWeight: "500" }],
        "currency-md": ["16px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "600" }],
        "display-lg-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
